---
title: "Plot in_vitro"
output: html_document
date: "2024-10-04"
editor_options:
  chunk_output_type: console
---


```{r setup, include=FALSE}
library(tidyverse)
library(reshape2)
library(pROC)
library(ggsignif)
library(cowplot)
rm(list = ls())
setwd("~/Library/Mobile Documents/com~apple~CloudDocs/Research/Aging/")

```



```{r}
pp="Current"
auc_mtx = NULL
cols = NULL
conversion = readRDS("./code/benchmark/method_names_conversion.rds")
datasets = c("human_IPF", "human_oral", "mouse_muscle", "mouse_testes", "mouse_lung_cancer","mouse_tauopathy", "mouse_heart_CMs", "mouse_heart_ECs")

# rename datasets
new_labels <- c(
  "Lung AT1",               # from "IPF_AT1" – no species removal here
  "Oral fibroblasts",       # from "oral_Fibroblasts"
  "Muscle endothelial",     # from "muscle_Endothelial"
  "Muscle satellite cells", # from "muscle_Satellite cells"
  "Muscle fibroblast",      # from "muscle_Fibroblast"
  "Muscle myonuclei",       # from "muscle_Myonuclei"
  "Muscle immune",          # from "muscle_Immune"
  "Muscle tendon cells",    # from "muscle_Tendon cells"
  "Muscle mural cells",     # from "muscle_Mural cells"
  "Testes Leydig cells",    # from "testes_Ld"
  "Lung macrophages",       # from "lung_cancer_Macrophages" -> drop "cancer"
  "Lung t cells",           # from "lung_cancer_T cells" -> drop "cancer"
  "Lung endothelial",       # from "lung_cancer_Endothelial" -> drop "cancer"
  "Lung AT2",               # from "lung_cancer_AT2" -> drop "cancer"
  "Lung fibroblasts",       # from "lung_cancer_Fibroblasts" -> drop "cancer"
  "Brain microglia",        # from "tauopathy_Micro"
  "Heart CMs",              # from "heart_CMs_CMs" -> take tissue "heart" and cell type from last part "CMs"
  "Heart ECs",              # from "heart_ECs_ECs"
  "Mean",                   # left as is
  "Significance"            # left as is
)

for (d in datasets) {
  # read all
  print(d)
  part1 = read.csv(paste0("./data/VADLIATION_DATA/IN_VIVO/", pp, "/metas/", d, "_scores_part1.csv"), row.names = 1)
  part2 = read.csv(paste0("./data/VADLIATION_DATA/IN_VIVO/", pp, "/metas/", d, "_scores_part2.csv"), row.names = 1)
  part1 = part1[rownames(part2),]
  s = cbind(part1, part2)
  
  # fix method names
  colnames(s) = plyr::mapvalues(colnames(s), names(conversion), conversion)
  cont_cols = colnames(s)[!colnames(s) %in% c("SID_binary", "y", "celltype")]
  
  # calculate auc by cell type
  for (ct in unique(s$celltype)) {
    s_ct = s[s$celltype==ct,]
    s_ct_cont = s_ct[,cont_cols]
    if (length(unique(s_ct$y)) < 2) {
      next
    }
    print(ct)
    print(table(s_ct$y))
    auc_values <- sapply(s_ct_cont, function(col) {
      roc_obj <- roc(s_ct$y, col, direction = "<")
      auc(roc_obj)
    })

    # append aucs
    auc_mtx = cbind(auc_mtx, auc_values)

    # append colnames
    col = paste0(d, "_", ct)
    cols = c(cols, col)
  }
}
colnames(auc_mtx) = cols

# in lung cancer data, require a ct have >200 cells and >=5 SnCs.
auc_mtx = auc_mtx[,!colnames(auc_mtx) %in%
                    c("mouse_lung_cancer_Smooth muscle cells", "mouse_muscle_Schwann cells")
]

auc_mtx = auc_mtx[!rownames(auc_mtx) %in% c("DeepScence:Casella et al.", "DeepScence:Freund et al.", "DeepScence:De Cecco et al."),]

names(new_labels) = c(colnames(auc_mtx), "mean", "sig")
```


```{r}
# get significance
pvals <- sapply(rownames(auc_mtx), function(method) {
  if(method == "DeepScence") {
    return(NA)  # ds_5. compared to itself gives NA
  } else {
    ttest_result <- t.test(auc_mtx[method, ], auc_mtx["DeepScence", ], paired = TRUE)
    return(ttest_result$p.value)
  }
})
# p.adj <- p.adjust(pvals, method = "bonferroni", n = length(pvals)-1)
p.adj = pvals 
p_sig <- ifelse(is.na(p.adj), NA,
                ifelse(p.adj < 0.001, "***",
                       ifelse(p.adj < 0.01, "**",
                              ifelse(p.adj < 0.05, "*", "NS"))))



df = as.data.frame(auc_mtx)
df$Mean <- apply(df, 1, mean, na.rm = TRUE)
df$method = rownames(df)
df <- df %>% 
  arrange(desc(-Mean))
df_long_auc <- melt(df, id.vars = 'method')
df_long_auc$method = factor(df_long_auc$method, levels = rownames(df))
df_long_auc$species = ifelse(startsWith(as.character(df_long_auc$variable), "human_"), "human", "mouse")
df_long_auc$p_label <- NA

df_sig <- data.frame(
  method = rownames(df),
  variable = "Significance",  # new x-axis level for p-value annotation
  value = 0.5,         # constant fill value so tile is white
  p_label = p_sig[rownames(df)],   # significance stars (or NA for DeepScence)
  species = "mouse"
  
)
df_long_auc_new <- rbind(df_long_auc, df_sig)
df_long_auc_new$variable <- factor(df_long_auc_new$variable,
                                   levels = c(setdiff(unique(df_long_auc_new$variable), "Significance"), "Significance"))



# create offset
levels_current <- levels(df_long_auc_new$variable)
n_levels <- length(levels_current)
positions <- 1:n_levels
positions[(n_levels-1):n_levels] <- positions[(n_levels-1):n_levels] + 0.5
position_lookup <- setNames(positions, levels_current)
df_long_auc_new$xpos <- position_lookup[as.character(df_long_auc_new$variable)]
levels_current <- sub("^[^_]*_", "", levels_current)

df1 = df_long_auc_new[!df_long_auc_new$method %in% c("DeepScence:3", "DeepScence:4", "DeepScence:6"),]
df2 = df_long_auc_new[df_long_auc_new$method %in% c("DeepScence:3", "DeepScence:4", "DeepScence:6", "DeepScence"),]
df = df1
```

```{r}
auc_plot <- ggplot() +
  geom_tile(data = subset(df, variable != "Significance"),
            aes(x = xpos, y = method, fill = value),
            color = 'black', alpha = 0.7, size = 0.4) +
  geom_tile(data = subset(df, variable == "Significance"),
            aes(x = xpos, y = method),
            fill = "white",
            color = 'black', alpha = 0.7, size = 0.4) +
  geom_text(data = df,
            aes(x = xpos, y = method, 
               label = ifelse(variable == "Significance", p_label, sprintf("%.2f", value))),
            color = "black") +
  scale_fill_distiller(palette = "YlOrRd", direction = 11) +
  labs(title = NULL, fill = "AUROC", x = "Datasets", y = "Methods", caption = "Datasets")  +
  theme_minimal() +
  facet_grid(. ~ species, scales = "free_x", space = "free_x", switch = "x") +
  scale_x_continuous(position = "top", breaks = positions, labels = levels_current, expand = c(0,0)) +
  theme(axis.title.x.bottom = element_blank(),
        axis.title.x.top = element_blank(),  
        axis.text.y = element_text(
          color = "black",
          size = 10, 
          face = ifelse(levels(factor(df$method)) == "DeepScence", "bold", "plain")
        ),
        axis.text.x.top = element_text(
          color = "black", 
          size = 10, angle = 20, hjust = 0.2, vjust=0.1,
          face = c(rep('plain', 16), "bold", "bold")
        ),
        axis.title.y = element_text(hjust = 0.8, size = 13),
        panel.background = element_blank(),
        panel.grid = element_blank(),
        legend.justification = c(1, 1.07),
        plot.caption = element_text(hjust = 0.5, size = 13)
  )
auc_plot
```


# additional plots (rocs and boxes)
```{r}
roc_plots <- list()
box_plots1 = list()
box_plots2 = list()
examples = c(
  "mouse_testes_Ld",
  "mouse_muscle_Satellite cells",
  "mouse_muscle_Fibroblast",
  "mouse_muscle_Myonuclei",
  "mouse_muscle_Immune",
  "mouse_muscle_Mural cells"
)

for (i in seq_along(examples)) {
  # Read both parts and merge them
  e = examples[i]
  d <- sub("^(.*)_.*$", "\\1", e)
  celltype <- sub(".*_(.*)$", "\\1", e)
  
  part1 <- read.csv(paste0("./data/VADLIATION_DATA/IN_VIVO/", pp, "/metas/", d, "_scores_part1.csv"), row.names = 1)
  part2 <- read.csv(paste0("./data/VADLIATION_DATA/IN_VIVO/", pp, "/metas/", d, "_scores_part2.csv"), row.names = 1)
  part1 <- part1[rownames(part2), ]
  s <- cbind(part1, part2)
  s = s[s$celltype==celltype,]
  
  # ROC plot
  roc1 <- roc(s$y, s$ds_5., direction = "<")
  roc2 <- roc(s$y, s$SID_score, direction = "<")
  roc3 <- roc(s$y, s$sensig_AUCell, direction = "<")
  roc4 <- roc(s$y, s$sensig_ssGSEA, direction = "<")
  roc5 <- roc(s$y, s$Quest_AUCell, direction = "<")
  
  proc <- ggroc(list(roc5, roc4, roc3, roc2, roc1), legacy.axes = TRUE) +
    theme_bw() +
    scale_color_manual(
      values = c("1" = "#64203C", "2" = "#175B59", "3" = "#2DAEBF", "4" = "#E19200", "5" = "red"),
      labels = c("1" = "AUCell:SeneQuest", "2" = "ssGESA:SenSig",
                 "3" = "AUCell:SenSig", "4" = "SenCID", "5" = "DeepScence"),
      breaks = c("5", "4", "3", "2", "1")
    ) +
    geom_abline(intercept = 0, slope = 1, color = "darkgrey", linetype = "dashed") +
    labs(subtitle = sub(" ", "\n", new_labels[e]), color = "Method") +
    guides(color = guide_legend(override.aes = list(linewidth = 2)))
  
  # append ROC plot
  i <- which(examples == e)
  if (i!=6) {
    proc <- proc + theme(legend.position = "none")
  }
  if (i != 1) {
    proc = proc + labs(y=NULL) + theme(
      axis.text.y = element_blank(),
      axis.ticks.y = element_blank()
    )
  }
  
  roc_plots[[i]] <- proc
  
  # Boxplot for ds vs. SID
  s_long <- s %>% 
    select(c("ds_5.", "SID_score", "y")) %>%
    pivot_longer(
      cols = c(ds_5., SID_score),
      names_to = "Method",
      values_to = "score"
    )
  s_long$dataset = sub(" ", "\n", new_labels[e])
  s_long$y = ifelse(s_long$y==1, "Disease", "Healthy")
  s_long$y = factor(s_long$y, levels = c("Healthy", "Disease"))
  p1 <- s_long %>%
    filter(Method == "ds_5.") %>%
    ggplot(aes(x = as.factor(y), y = score, fill=as.factor(y))) +
    geom_violin(alpha=0.8, scale="width") +
    geom_signif(comparisons = list(c("Healthy", "Disease")),
                test = "t.test",
                map_signif_level = TRUE,
                y_position = max(s$ds_5.)) +
    scale_fill_manual(values = c("Healthy" = "#45caff", "Disease" = "#ff1b6b")) +
    facet_wrap(~ dataset, scales = "free") +
    labs(x = NULL, y=NULL, fill="Condition") +
    expand_limits(y = min(s$ds_5.) + (max(s$ds_5.) - min(s$ds_5.)) * 1.2) +
    theme_bw()
  p2 <- s_long %>%
    filter(Method == "SID_score") %>%
    ggplot(aes(x = as.factor(y), y = score, fill=as.factor(y))) +
    geom_violin(alpha=0.8, scale="width") +
    geom_signif(comparisons = list(c("Healthy", "Disease")),
                test = "t.test",
                map_signif_level = TRUE,
                y_position = max(s$SID_score)) +
    scale_fill_manual(values = c("Healthy" = "#45caff", "Disease" = "#ff1b6b")) +
    # facet_wrap(~ dataset, scales = "free") +
    labs(x = "Condition", y=NULL, fill="Condition") +
    expand_limits(y = min(s$SID_score) + (max(s$SID_score) - min(s$SID_score)) * 1.2) +
    theme_bw()
  
  if (i==1) {
    p1 = p1+labs(y="DeepScence\nscore")
    p2 = p2+labs(y="SenCID\nscore")
  }
  if (i != 6) {
    p1 <- p1 + theme(legend.position = "none")
    p2 <- p2 + theme(legend.position = "none")
  }
  
  box_plots1[[i]] = p1
  box_plots2[[i]] = p2
  
}
p_rocs <- wrap_plots(roc_plots, nrow = 1) + plot_layout(axis_titles = "collect")
p_boxs1 <- wrap_plots(box_plots1, nrow = 1) + plot_layout(axis_titles = "collect")
p_boxs2 <- wrap_plots(box_plots2, nrow = 1) + plot_layout(axis_titles = "collect")
p_boxs1/p_boxs2
```

# fig4. 
```{r}
p_box <- p_boxs1 / p_boxs2 + 
  plot_layout(axis_titles = "collect", guides = "collect")
combined <- p_rocs / p_box +
  plot_layout(heights = c(1, 2))
f4 <- plot_grid(auc_plot, combined, ncol = 1, align = "none", rel_heights = c(1, 0.8))
ggsave("./manuscript/new_figures/f4.png", plot = f4, width = 11*(5/4), height = 11, dpi = 300)
# ggsave("./manuscript/new_figures/f4_sup.png", plot = f4, width = 11*(5/4), height = 11, dpi = 300)
```

# Human normal aging plot
```{r}

```


# fig6. driving gene 
```{r}
gs = readRDS("./data/coreGS_v2.rds")
gs = gs[gs$n>=5,]

df = t(read.csv("./data/driving_genes.csv", row.names = 1))
df_for_cluster <- df
df_for_cluster[is.na(df_for_cluster)] <- 0
row_order <- hclust(dist(df_for_cluster))$order
col_order <- hclust(dist(t(df_for_cluster)))$order
df_ordered <- df[row_order, col_order]
df_long <- melt(df_ordered)
names(df_long) <- c("gene", "dataset", "correlation")
df_long$gene <- factor(df_long$gene, levels = rownames(df_ordered))
df_long$dataset <- factor(df_long$dataset, levels = colnames(df_ordered))

# add direction
df_long$direction = plyr::mapvalues(df_long$gene, rownames(gs), gs$direction)
df_long$species = ifelse(grepl("mouse_", df_long$dataset), 'Mouse', "Human")

p1 = ggplot(df_long, aes(x = dataset, y = gene, color = correlation, size = abs(correlation))) +
  geom_point() +
  scale_size(range = c(1, 3.5)) +
  scale_color_gradient2(low = "blue", mid = "white", high = "red", midpoint = 0) +
  theme_bw() +
  labs(x = "Dataset", y = "Gene", color = "Correlation", size = "Absolute\nCorrelation") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  facet_grid(direction ~ species, scales = "free", space = "free")

# corr

df_summary <- df_long %>%
  group_by(gene) %>%
  summarize(
    mean_rank = mean(correlation, na.rm = TRUE),
    sd_rank   = sd(correlation, na.rm = TRUE)
  )

p2 <- ggplot(df_summary, aes(x = reorder(gene, -mean_rank), y = mean_rank, color = gene)) +
  geom_point(size = 3) +
  geom_errorbar(aes(ymin = mean_rank - sd_rank, ymax = mean_rank + sd_rank), width = 0.2) +
  theme_bw() +
  labs(x = "Gene", y = "Mean Corr ± SD") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        legend.position = "none")


# rank
df_long <- df_long %>%
  group_by(dataset) %>%
  mutate(rank = rank(-abs(correlation), ties.method = "min")) %>%
  ungroup()

gene_means <- df_long %>%
  group_by(gene) %>%
  summarize(mean = mean(rank, na.rm = TRUE)) %>%
  arrange(-mean)
df_summary <- df_long %>%
  group_by(gene) %>%
  summarize(
    mean_rank = mean(rank, na.rm = TRUE),
    sd_rank   = sd(rank, na.rm = TRUE)
  )

p3 <- ggplot(df_summary, aes(x = reorder(gene, -mean_rank), y = mean_rank, color = gene)) +
  geom_point(size = 3) +
  geom_errorbar(aes(ymin = mean_rank - sd_rank, ymax = mean_rank + sd_rank), width = 0.2) +
  theme_bw() +
  labs(x = "Gene", y = "Mean Rank ± SD") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        legend.position = "none")
p3
```


# sup sensitivity
```{r}
s1 = readRDS("./manuscript/new_figures/sensitivity1.rds")
s2 = readRDS("./manuscript/new_figures/sensitivity2.rds")
s3 = readRDS("./manuscript/new_figures/sensitivity3.rds")
s3 <- s3 + theme(
  axis.text.x.top = element_text(
    angle = 30,
    vjust = 0,
    hjust = 0
  )
)
s <- (s1 | s3) / s2 + plot_layout(guides = "collect")

```

