---
title: "DeepScence fig5"
output: html_document
date: "2024-10-04"
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(Seurat)
library(pROC)
library(reshape2)
library(cowplot)
library(patchwork)
library(ggsignif)
rm(list = ls())
setwd("~/Library/Mobile Documents/com~apple~CloudDocs/Research/Aging/")
```

# Visium

```{r}
load('./data/in_vivo/sp_mouse_injury/vis_slim_v1.RData')
d2 = vis.list[[1]]
d5 = vis.list[[2]]
d7 = vis.list[[3]]
# ctx = Load10X_Spatial(
#   data.dir = "./data/in_vivo/sp_mouse_injury/outs/",
#   image = Read10X_Image("./data/in_vivo/sp_mouse_injury/outs/spatial/")
# )
# ctx.meta = read.csv("./data/in_vivo/sp_mouse_injury/ctx_metadata_scored.csv", row.names = 1)
# ctx = ctx[,rownames(ctx.meta)]
# ctx@meta.data = ctx.meta
# saveRDS(ctx, "./data/in_vivo/sp_mouse_injury/ctx_scored_final.rds")
ctx = readRDS("./data/in_vivo/sp_mouse_injury/ctx_scored_final.rds")
```

```{r}1
# raw_counts = GetAssayData(adata, layer="counts")
# current_row_names <- rownames(raw_counts)
# new_row_names <- ifelse(current_row_names %in% names(mouse_to_human),
#                         mouse_to_human[current_row_names],
#                         current_row_names)
# rownames(raw_counts) = new_row_names
# write.csv(as.matrix(raw_counts), file = "./data/in_vivo/sp_mouse_injury/d5_human_gene.csv")
# metadata <- d5@meta.data
# write.csv(metadata, file = "./data/in_vivo/sp_mouse_injury/d5_metadata.csv")
```

```{r}
adata = d2
adata@active.assay = "Spatial"

meta = read.csv("./data/in_vivo/sp_mouse_injury/d2_scored_meta.csv", row.names = 1)
meta$is.injury = ifelse(meta$is.injury=="True", "Injured", "Healthy")
adata@meta.data = meta
Idents(adata) = adata$is.injury

sp1_1 = SpatialDimPlot(adata, pt.size.factor = 2, label = T, label.size = 4, repel = F) +
  coord_equal()  +
  scale_fill_manual(values = c("#45caff", "#ff1b6b")) + NoLegend()

sp2_1 = SpatialFeaturePlot(adata, "ds", pt.size.factor = 2.5) +
  labs(fill="DeepScence") + 
  coord_equal() +
  NoLegend()

sp3_1 = SpatialFeaturePlot(adata, "sid_score", pt.size.factor = 2.5) +
  labs(fill="SenCID") + 
  coord_equal()  +
  NoLegend()

roc_ds = roc(as.numeric(meta$is.injury == "Injured"), meta$ds, direction = "<")
roc_sid = roc(as.numeric(meta$is.injury == "Injured"), meta$sid_score, direction="<")
rocs = list(DeepScence = roc_ds, SenCID = roc_sid)
proc_1 = ggroc(rocs, legacy.axes = TRUE) +
    theme_bw() +
    scale_color_manual(values = c("red", "#E19200")) +
    geom_abline(intercept = 0, slope = 1, color = "darkgrey", linetype = "dashed") +
    labs(color=NULL) +
  
    scale_x_continuous(breaks = c(0, 0.5, 1)) + 
    scale_y_continuous(breaks = c(0, 0.5, 1)) + 
    guides(color = "none")

vio1_1 = ggplot(meta, aes(x = is.injury, y = ds, fill = is.injury)) + 
  geom_violin(color="black", alpha=0.8, scale = "width") +
  scale_fill_manual(values = c("#45caff", "#ff1b6b")) +
  labs(x = "Condition", y = "DeepScence\nscore", fill = NULL) +
  geom_signif(
            comparisons = list(c("Injured", "Healthy")),
            map_signif_level=TRUE, test = "wilcox.test",
            y_position = max(meta$ds)
          ) +
  expand_limits(y = min(meta$ds) + (max(meta$ds) - min(meta$ds)) * 1.2) +
  theme_bw() +
  guides(fill = "none")

vio2_1 = ggplot(meta, aes(x = is.injury, y = sid_score, fill = is.injury)) + 
  geom_violin(color="black", alpha=0.8, scale = "width") +
  scale_fill_manual(values = c("#45caff", "#ff1b6b")) +
  labs(x = "Condition", y = "SenCID\nscore", fill = NULL) +
  geom_signif(
            comparisons = list(c("Injured", "Healthy")),
            map_signif_level=TRUE, test = "wilcox.test",
            y_position = max(meta$sid_score)
          ) +
  expand_limits(y = min(meta$sid_score) + (max(meta$sid_score) - min(meta$sid_score)) * 1.2) +
  theme_bw()+
  guides(fill = "none") +
  theme(legend.position = "bottom")
```

```{r}
adata = d5
adata@active.assay = "Spatial"

meta = read.csv("./data/in_vivo/sp_mouse_injury/d5_scored_meta.csv", row.names = 1)
meta$celltype = "spatial"
meta$is.injury = ifelse(meta$is.injury=="True", "Injured", "Healthy")
adata@meta.data = meta
Idents(adata) = adata$is.injury

sp1_2 = SpatialDimPlot(adata, pt.size.factor = 2, label = T, label.size = 4, repel = F) +
  labs(fill="Condition") +
  coord_equal()  +
  scale_fill_manual(values = c("#45caff", "#ff1b6b")) +
  NoLegend()

sp2_2 = SpatialFeaturePlot(adata, "ds", pt.size.factor = 2.5) +
  labs(fill="DeepScence") + 
  coord_equal() +
  NoLegend()

sp3_2 = SpatialFeaturePlot(adata, "sid_score", pt.size.factor = 2.5) +
  labs(fill="SenCID") + 
  coord_equal()  +
  NoLegend()
roc_ds = roc(as.numeric(meta$is.injury == "Injured"), meta$ds, direction = "<")
roc_sid = roc(as.numeric(meta$is.injury == "Injured"), meta$sid_score, direction="<")
rocs = list(DeepScence = roc_ds, SenCID = roc_sid)
proc_2 = ggroc(rocs, legacy.axes = TRUE) +
    theme_bw() +
    scale_color_manual(values = c("red", "#E19200")) +
    geom_abline(intercept = 0, slope = 1, color = "darkgrey", linetype = "dashed") +
    labs(color=NULL) +
    scale_x_continuous(breaks = c(0, 0.5, 1)) + 
    scale_y_continuous(breaks = c(0, 0.5, 1)) + 
    guides(color = "none") 

vio1_2 = ggplot(meta, aes(x = is.injury, y = ds, fill = is.injury)) + 
  geom_violin(color="black", alpha=0.8, scale = "width") +
  scale_fill_manual(values = c("#45caff", "#ff1b6b")) +
  labs(x = "Condition", y = "DeepScence\nscore", fill = NULL) +
  geom_signif(
            comparisons = list(c("Injured", "Healthy")),
            map_signif_level=TRUE, test = "wilcox.test",
            y_position = max(meta$ds)
          ) +
  expand_limits(y = min(meta$ds) + (max(meta$ds) - min(meta$ds)) * 1.2) +
  theme_bw() +
  guides(fill = "none")

vio2_2 = ggplot(meta, aes(x = is.injury, y = sid_score, fill = is.injury)) + 
  geom_violin(color="black", alpha=0.8, scale = "width") +
  scale_fill_manual(values = c("#45caff", "#ff1b6b")) +
  labs(x = "Condition", y = "SenCID\nscore", fill = NULL) +
  geom_signif(
            comparisons = list(c("Injured", "Healthy")),
            map_signif_level=TRUE, test = "wilcox.test",
            y_position = max(meta$sid_score)
          ) +
  expand_limits(y = min(meta$sid_score) + (max(meta$sid_score) - min(meta$sid_score)) * 1.2) +
  theme_bw()+
  guides(fill = "none")
```

```{r}
adata = ctx
adata$condition[adata$condition == "Uninjured"] = "Healthy"
Idents(adata) = adata$condition

sp1_3 = SpatialDimPlot(adata, pt.size.factor = 1.7, label = T, label.size = 4, repel = T) +
  coord_equal()  +
  scale_fill_manual(values = c("#ff1b6b","#45caff", "#8d99ae")) + 
  labs(fill="Condition")+
  guides(fill = guide_legend(override.aes = list(size = 3), nrow=3)) +
  theme(legend.position = "bottom",
        legend.title = element_text(size = 10),
        legend.text = element_text(size = 8),
        legend.key.size = unit(0.5, "cm")
        ) 

sp2_3 = SpatialFeaturePlot(adata, "ds", pt.size.factor = 2) +
  labs(fill="DeepScence") + 
  coord_equal() +
  theme(legend.position = "bottom",
        legend.key.height = unit(0.5, "cm"),
        legend.key.width = unit(0.4, "cm"),
        legend.title = element_text(size = 10),
        legend.text = element_text(size = 8))

sp3_3 = SpatialFeaturePlot(adata, "sid_score", pt.size.factor = 2) +
  labs(fill="SenCID") + 
  coord_equal()  +
  theme(legend.position = "bottom",
        legend.key.height = unit(0.5, "cm"),
        legend.key.width = unit(0.4, "cm"),
        legend.title = element_text(size = 10),
        legend.text = element_text(size = 8))

meta = adata@meta.data
meta = meta[meta$condition!= "Newly repaired",]
meta$condition[meta$condition == "Uninjured"] = "Healthy"
meta$condition = factor(meta$condition, levels = c("Healthy", "Injured"))

roc_ds = roc(as.numeric(meta$condition == "Injured"), meta$ds, direction = "<")
roc_sid = roc(as.numeric(meta$condition == "Injured"), meta$sid_score, direction="<")
rocs = list(DeepScence = roc_ds, SenCID = roc_sid)

proc_3 = ggroc(rocs, legacy.axes = TRUE) +
    theme_bw() +
    scale_color_manual(values = c("red", "#E19200")) +
    geom_abline(intercept = 0, slope = 1, color = "darkgrey", linetype = "dashed") +
    labs(color="Methods") +
    scale_x_continuous(breaks = c(0, 0.5, 1)) + 
    scale_y_continuous(breaks = c(0, 0.5, 1)) + 
    guides(color = guide_legend(override.aes = list(linewidth = 1.5), nrow=2)) +
    theme(legend.position = "bottom") 

vio1_3 = ggplot(meta, aes(x = condition, y = ds, fill = condition)) + 
  geom_violin(color="black", alpha=0.8, scale = "width") +
  scale_fill_manual(values = c("#45caff", "#ff1b6b")) +
  labs(x = "Condition", y = "DeepScence\nscore", fill = "Condition") +
  geom_signif(
            comparisons = list(c("Injured", "Healthy")),
            map_signif_level=TRUE, test = "wilcox.test",
            y_position = max(meta$ds)
          ) +
  expand_limits(y = min(meta$ds) + (max(meta$ds) - min(meta$ds)) * 1.2) +
  theme_bw() +
  guides(fill = guide_legend(nrow=2)) +
  theme(legend.position = "bottom")

vio2_3 = ggplot(meta, aes(x = condition, y = sid_score, fill = condition)) + 
  geom_violin(color="black", alpha=0.8, scale = "width") +
  scale_fill_manual(values = c("#45caff", "#ff1b6b")) +
  labs(x = "Condition", y = "SenCID\nscore", fill = "Condition") +
  geom_signif(
            comparisons = list(c("Injured", "Healthy")),
            map_signif_level=TRUE, test = "wilcox.test",
            y_position = max(meta$sid_score)
          ) +
  expand_limits(y = min(meta$sid_score) + (max(meta$sid_score) - min(meta$sid_score)) * 1.2) +
  theme_bw()+
  guides(fill = guide_legend(nrow=2)) +
  theme(legend.position = "bottom")
```


```{r}
sp1_1/sp1_2/sp1_3
sp2_1/sp2_2/sp2_3
vio1_1/vio1_2/vio1_3
sp3_1/sp3_2/sp3_3
vio2_1/vio2_2/vio2_3
proc_1/proc_2/proc_3
```


```{r}1
path = "./data/in_vivo/sp_mouse_injury/outs/"
adata = Load10X_Spatial(
      data.dir = path,
      filename = "filtered_feature_bc_matrix.h5",
      image = Read10X_Image(image.dir = paste0(path,"spatial/"), image.name = "tissue_lowres_image.png")
    )
adata = adata[,adata$nCount_Spatial > 1000]
adata = adata[,adata$nFeature_Spatial > 500]
```



# Xenium
```{r}
folder_path <- "./data/Xenium/results/"
file_list <- list.files(path = folder_path, pattern = "*.csv", full.names = TRUE)
plot_list <- list()

for (i in seq_along(file_list)) {
  file <- file_list[i]
  study_name <- gsub("_results.csv", "", basename(file))
  df <- read.csv(file)
  df$study_name = study_name
  df$genes_added = as.factor(df$genes_added)
  df_medians_deepscence <- df %>%
    filter(method == "DeepScence") %>%
    group_by(genes_added) %>%
    summarize(Median_AUROC = median(AUC))
  df_medians_SenCID <- df %>%
    filter(method == "SenCID") %>%
    group_by(genes_added) %>%
    summarize(Median_AUROC = median(AUC))
  df = df[df$genes_added!="10",]
  df$pair = paste0(df$method, df$genes_added)
  df$pair <- factor(df$pair, levels = c("DeepScence20", "SenCID20", "DeepScence30", "SenCID30", "DeepScence40", "SenCID40"))
  comparisons = list(
    c("DeepScence20", "SenCID20"),
    c("DeepScence30", "SenCID30"),
    c("DeepScence40", "SenCID40")
  )
  
  plot <- ggplot(df, aes(x = pair, y = AUC, fill= method)) +
    geom_violin(color="black", alpha=0.8, scale = "width", adjust=4) +
    scale_fill_manual(values = c("DeepScence" = "red", "SenCID" = "#FFB120")) + 
    facet_grid(.~study_name, scales = "free") + 
    geom_signif(
            comparisons = comparisons,
            map_signif_level=TRUE, test = "wilcox.test",
            y_position = max(df$AUC)
          ) +
    ylim(0.5,1.05) + 
    labs(x = "Number of senescence-associated genes added to gene panel", y = NULL, color=NULL, fill="Methods") +
    theme_bw() +
    scale_x_discrete(
        breaks = levels(df$pair),  
        labels = c("10", "", "20", "", "30", "")
    ) +
    theme(panel.grid.minor = element_blank(),
          axis.text.x = element_text(hjust = -0.45))
    
  
  if (i != length(file_list)) {
    plot <- plot + theme(legend.position = "none")
  }
  if (i == 1) {
    plot <- plot + labs(y = "AUROC")
  }
  plot_list[[study_name]] <- plot
}

combined_plot <- wrap_plots(plot_list, ncol = length(plot_list)) + plot_layout(axis_titles = "collect")
print(combined_plot)
```


