---
title: "DeepScence fig. 4"
output: html_document
date: "2024-10-01"
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(Seurat)
library(pROC)
library(cowplot)
library(patchwork)
library(reshape2)
rm(list = ls())
setwd("~/Library/Mobile Documents/com~apple~CloudDocs/Research/Aging/")
```


# Get all AUROCs

score columns
```{r}
folder = "./data/in_vivo/scored_rds/"
score_columns = c("ds", "sid_score", "ssGSEA_CoreScence", "ssGSEA_senmayo", "ssGSEA_cellAge", "ssGSEA_geneAge", "ssGSEA_csgene", "ssGSEA_cellsig", "ssGSEA_quest", "ssGSEA_sasp", "ssGSEA_trans", "AUCell_CoreScence", "AUCell_senmayo", "AUCell_cellAge", "AUCell_geneAge", "AUCell_csgene", "AUCell_cellsig", "AUCell_quest", "AUCell_sasp", "AUCell_trans", "CDKN1A", "CDKN2A" )
all.result = NULL
roc.list = list()
plot.list = list()

```

mouse testes
```{r}
mouse_testes = readRDS("./data/in_vivo/scored_rds/mouse_testes.rds")
mouse_testes$condition = ifelse(mouse_testes$stim == "O50t", "diseased", "healthy")
mouse_testes$condition = factor(mouse_testes$condition, levels = c("healthy", "diseased"))
auroc_values <- numeric(length(score_columns))
roc.list[["Leydig"]] = list()

for (i in seq_along(score_columns)) {
  score_col <- score_columns[i]
  if (score_col %in% colnames(mouse_testes@meta.data)) {
    roc_result <- roc(mouse_testes$condition == "diseased", mouse_testes@meta.data[,score_col], direction="<")
    auroc_values[i] <- auc(roc_result)
    
    # save roc
    if (score_columns[i] %in% c("ds", "sid_score", "AUCell_cellsig", "AUCell_quest", "ssGSEA_cellsig")) {
      roc.list[["Leydig"]][[score_columns[i]]] = roc_result
    }
    
    mouse_testes$subtype = "Mouse\nLeydig cells"
    # save plot
    p1 = ggplot(mouse_testes@meta.data, aes(x = as.factor(condition), y = ds, fill = as.factor(condition))) + 
      geom_violin(color="black", alpha=0.8, scale = "width") +
      scale_fill_manual(values = c("#45caff", "#ff1b6b")) +
      labs(x = "Condition", y = "DeepScence\nscore", fill = "Condition") +
      geom_signif(
        comparisons = list(c("diseased", "healthy")),
        map_signif_level=TRUE, test = "wilcox.test", 
        y_position =max(mouse_testes$ds)
      ) +
      facet_wrap(~subtype, scales = "free", nrow = 1) +
      expand_limits(y = min(mouse_testes$ds) + (max(mouse_testes$ds) - min(mouse_testes$ds)) * 1.2) +
      theme_bw()
  
    p2 = ggplot(mouse_testes@meta.data, aes(x = as.factor(condition), y = sid_score, fill = as.factor(condition))) + 
      geom_violin(color="black", alpha=0.8, scale = "width") +
      scale_fill_manual(values = c("#45caff", "#ff1b6b")) +
      labs(x = "Condition", y = "SenCID\nscore", fill = "Condition") +
      geom_signif(
        comparisons = list(c("diseased", "healthy")),
        map_signif_level=TRUE, test = "wilcox.test",
        y_position = max(mouse_testes$sid_score)
      ) +
      facet_wrap(~subtype, scales = "free", nrow = 1) +
      expand_limits(y = min(mouse_testes$sid_score) + (max(mouse_testes$sid_score) - min(mouse_testes$sid_score)) * 1.2) +
      theme_bw()
    print(p1/p2)
    plot.list[["ds_ld"]] = p1
    plot.list[["sid_ld"]] = p2
    
  } else {
    print("not in")
    auroc_values[i] <- NA
  }
}

all.result = rbind(all.result, auroc_values)
```

mouse injury
```{r}

mouse_injury = readRDS("./data/in_vivo/scored_rds/mouse_injury.rds")
mouse_injury$condition = ifelse(mouse_injury$stim == "CTX", "diseased", "healthy")
mouse_injury$condition = factor(mouse_injury$condition, levels = c("healthy", "diseased"))
celltypes = unique(mouse_injury$cluster)
new.celltypes = c("Endothelial", "Mouse\nSatellite cells", "Mouse\nFibroblasts", "Mouse\nMyonuclei", "Mouse\nImmune cells", "Tendon cells", "Mouse\nMural cells", "Schwann cells")
mouse_injury$cluster = plyr::mapvalues(mouse_injury$cluster, celltypes, new.celltypes)

auroc_all = NULL
for (ct in unique(mouse_injury$cluster)) {
  this.ct = mouse_injury[,mouse_injury$cluster == ct]
  auroc_values <- numeric(length(score_columns))
  for (i in seq_along(score_columns)) {
    score_col <- score_columns[i]
    if (score_col %in% colnames(this.ct@meta.data)) {
      roc_result <- roc(this.ct$condition == "diseased", this.ct@meta.data[,score_col], direction="<")
      
      if (grepl("Mouse\n", ct)) {
        
        # save roc
        if (score_columns[i] %in% c("ds", "sid_score", "AUCell_cellsig", "AUCell_quest", "ssGSEA_cellsig")) {
          roc.list[[ct]][[score_columns[i]]] = roc_result
        }
        # save plot
        this_ct = mouse_injury[,mouse_injury$cluster==ct]
        p1 = ggplot(this_ct@meta.data, aes(x = as.factor(condition), y = ds, fill = as.factor(condition))) + 
          geom_violin(color="black", alpha=0.8, scale = "width") +
          scale_fill_manual(values = c("#45caff", "#ff1b6b")) +
          labs(x = "Condition", y = "DeepScence\nscore", fill = "Condition") +
          geom_signif(
            comparisons = list(c("diseased", "healthy")),
            map_signif_level=TRUE, test = "wilcox.test",
            y_position = max(this_ct$ds)
          ) +
          facet_wrap(~cluster, scales = "free", nrow = 1) +
          expand_limits(y = min(this_ct$ds) + (max(this_ct$ds) - min(this_ct$ds)) * 1.2) +
          theme_bw()
      
        p2 = ggplot(this_ct@meta.data, aes(x = as.factor(condition), y = sid_score, fill = as.factor(condition))) + 
          geom_violin(color="black", alpha=0.8, scale = "width") +
          scale_fill_manual(values = c("#45caff", "#ff1b6b")) +
          labs(x = "Condition", y = "SenCID\nscore", fill = "Condition") +
          geom_signif(
            comparisons = list(c("diseased", "healthy")),
            map_signif_level=TRUE, test = "wilcox.test",
            y_position = max(this_ct$sid_score)
          ) +
          facet_wrap(~cluster, scales = "free", nrow = 1) +
          expand_limits(y = min(this_ct$sid_score) + (max(this_ct$sid_score) - min(this_ct$sid_score)) * 1.2) +
          theme_bw()
        plot.list[[paste0("ds_",ct)]] = p1
        plot.list[[paste0("sid_", ct)]] = p2
      }
      
      
      auroc_values[i] <- auc(roc_result)
    } else {
      print("not in")
      auroc_values[i] <- NA
    }
  }
  auroc_all = rbind(auroc_all, auroc_values)
}


all.result = rbind(all.result, auroc_all)
```


human IPF
```{r}
human_IPF = readRDS("./data/in_vivo/scored_rds/human_IPF.rds")
human_IPF$condition = ifelse(human_IPF$health_status == "IPF", "diseased", "healthy")
auroc_values <- numeric(length(score_columns))
for (i in seq_along(score_columns)) {
  score_col <- score_columns[i]
  if (score_col %in% colnames(human_IPF@meta.data)) {
    roc_result <- roc(human_IPF$condition == "diseased", human_IPF@meta.data[,score_col], direction="<")
    auroc_values[i] <- auc(roc_result)
  } else {
    print("not in")
    auroc_values[i] <- NA
  }
}

all.result = rbind(all.result, auroc_values)
```

human oral
```{r}
human_oral = readRDS("./data/in_vivo/scored_rds/human_oral.rds")
human_oral$condition = ifelse(human_oral$Condition == "periodontitis", "diseased", "healthy")
auroc_values <- numeric(length(score_columns))
for (i in seq_along(score_columns)) {
  score_col <- score_columns[i]
  if (score_col %in% colnames(human_oral@meta.data)) {
    roc_result <- roc(human_oral$condition == "diseased", human_oral@meta.data[,score_col], direction="<")
    auroc_values[i] <- auc(roc_result)
  } else {
    print("not in")
    auroc_values[i] <- NA
  }
}

all.result = rbind(all.result, auroc_values)
```

Collect all results
```{r}
rownames(all.result) = c(
  "Mouse Leydig", 
  paste("Mouse", gsub(" cells", "", unique(mouse_injury$cluster))),
  "Human AT1",
  "Human fibroblasts"
)
score_columns[1:2] = c("DeepScence", "SenCID")
score_columns[3:20] = gsub("_", ": ", score_columns[3:20])
score_columns[21:22] = paste("SingleMarker: ", score_columns[21:22])
colnames(all.result) = score_columns

results_df = as.data.frame(all.result)
colnames(results_df) = c(
  "DeepScence", "SenCID", "ssGSEA: CoreScence", "ssGSEA: SenMayo", 
  "ssGSEA: CellAge", "ssGSEA: GenAge", "ssGSEA: CSGene", "ssGSEA: SenSig", 
  "ssGSEA: SeneQuest", "ssGSEA: De Cecco et al.", "ssGSEA: Casella et al.", "AUCell: CoreScence", 
  "AUCell: SenMayo", "AUCell: CellAge", "AUCell: GenAge", "AUCell: CSGene", 
  "AUCell: SenSig", "AUCell: SeneQuest", "AUCell: De Cecco et al.", "AUCell: Casella et al.", 
  "SingleMarker: CDKN1A", "SingleMarker: CDKN2A"
)
results_df$cell_type = rownames(results_df) 
results_df <- melt(results_df, id.vars = "cell_type", variable.name = "Method", value.name = "Score")

for (i in 1:length(roc.list)) {
  names(roc.list[[i]]) = c("DeepScence", "SenCID", "AUCell: SenSig", "AUCell: SeneQuest", "ssGSEA: SenSig")
}
saveRDS(results_df, "./data/in_vivo/results/AUC_all.rds")
saveRDS(roc.list, "./data/in_vivo/results/roc_curves.rds")
saveRDS(plot.list, "./data/in_vivo/results/boxplots.rds")
```





# Visualize
```{r}
df <- readRDS("./data/in_vivo/results/AUC_all.rds")

method_means <- aggregate(Score ~ Method, data = df, FUN = mean)
mean_rows <- data.frame(Method = method_means$Method, 
                        cell_type = "mean", 
                        Score = method_means$Score)
df <- rbind(df, mean_rows)

# Step 2: Order 'Method' by decreasing method level mean
df$Method <- factor(df$Method, levels = method_means$Method[order(method_means$Score)])
df$cell_type <- factor(df$cell_type, levels = c(setdiff(unique(df$cell_type), "mean"), "mean"))
df$organism = ifelse(grepl("Mouse", df$cell_type), "Mouse", "Human")
df$organism[df$cell_type == "mean"] = "mean"
df$organism = factor(df$organism, levels = c("Human", "Mouse", "mean"))
df$cell_type = gsub(".* ", "", df$cell_type)
df = df[!grepl("CoreScence", df$Method),]
n_methods = length(unique(df$Method))
n_celltypes = length(unique(df$cell_type))
convert = data.frame(
  originals = c("AT1", "fibroblasts", "Endothelial", "Fibroblast", "Immune", "Leydig", "Mural", "Myonuclei", "Satellite", "Schwann", "Tendon", "mean"), 
  new = c("AT1\ncells", "Fibroblasts ", "Endothelial\ncells", "Fibroblasts", "Immune\ncells", "Leydig\ncells", "Mural\ncells", "Myonuclei", "Satellite\ncells", "Schwann\ncells", "Tendon\ncells", "Mean")
)
df$cell_type = plyr::mapvalues(df$cell_type, convert$originals, convert$new)

auc_plot = ggplot(df, aes(x = cell_type, y = Method, fill = Score)) +
  geom_tile(color='black', alpha=0.8, size=0.4) +
  geom_text(aes(label = sprintf("%.2f", Score)), color = "black") +
  facet_grid(. ~ organism, scales = "free_x", space = "free_x") +
  scale_fill_distiller(palette = "RdYlGn", direction = 11) +
  labs(title = NULL, fill = "AUROC", x = "Cell types", y = "Methods")  +
  theme(
    axis.text.x = element_text(margin = margin(t = -1), color = "black", face=c(rep('plain',10), "bold"), angle = 0),
    axis.text.y = element_text(margin = margin(l = -1), color="black", face=c(rep('plain',n_methods-1), "bold")),
    axis.ticks = element_blank(),
    axis.title.y = element_text(hjust = 0.8),
    panel.background = element_blank(),
    panel.grid = element_blank(),
    legend.justification = c(1, 1.07),
  )
auc_plot
```

# roc curves
```{r}
roc.list = readRDS("./data/in_vivo/results/roc_curves.rds")
boxplot.list = readRDS("./data/in_vivo/results/boxplots.rds")
roc.plots = list()
celltypes = c("Mouse\nLeydig cells", "Mouse\nSatellite cells", "Mouse\nFibroblasts", "Mouse\nMyonuclei", "Mouse\nImmune cells", "Mouse\nMural cells")
for (i in seq_along(names(roc.list))) {
  name = names(roc.list)[i]
  rocs = rev(roc.list[[name]])

  # Create the ROC plot
  proc = ggroc(rocs, legacy.axes = TRUE) +
    theme_bw() +
    scale_color_manual(
      values = c("red", "#E19200", "#2DAEBF", "#175B59", "#64203C"),
      breaks = c("DeepScence", "SenCID", "AUCell: SenSig", "AUCell: SeneQuest", "ssGSEA: SenSig")
    ) +
    geom_abline(intercept = 0, slope = 1, color = "darkgrey", linetype = "dashed") +
    labs(subtitle = celltypes[i], color="Methods") +
    scale_x_continuous(breaks = c(0, 0.5, 1)) + 
    scale_y_continuous(breaks = c(0, 0.5, 1)) + 
    guides(color = guide_legend(override.aes = list(linewidth = 1.5))) + 
    theme(
      legend.text = element_text(size = 9)
    )
  if (i!=6) {
    proc <- proc + theme(legend.position = "none")
  }
  if (i != 1) {
    proc = proc + labs(y=NULL) + theme(
      axis.text.y = element_blank(),
      axis.ticks.y = element_blank()
      )
  }
  
  roc.plots[[i]] = proc  # Append plot to the list
}
roc.plots_combined <- wrap_plots(roc.plots, nrow = 1) + plot_layout(axis_titles = "collect")

ds_plots <- boxplot.list[grep("^ds_", names(boxplot.list))]
sid_plots <- boxplot.list[grep("^sid_", names(boxplot.list))]
for (i in seq_along(ds_plots)) {
  ds_plots[[i]] <- ds_plots[[i]] +
    theme(axis.text.x = element_text(angle = 20, hjust=0.7))
  if (i != 1) {
    ds_plots[[i]] <- ds_plots[[i]] + labs(y = NULL) 
  }
  if (i == length(ds_plots)) {
    ds_plots[[i]] <- ds_plots[[i]] + guides(fill = "legend") + labs(fill="Condition")
  }
}

for (i in seq_along(sid_plots)) {
  sid_plots[[i]] <- sid_plots[[i]] + 
    labs(x=NULL) +
    theme(axis.text.x = element_blank(),
          axis.ticks.x = element_blank())
  if (i != 1) {
    sid_plots[[i]] <- sid_plots[[i]] + labs(y = NULL)
  }
  if (i == length(sid_plots)) {
    sid_plots[[i]] <- sid_plots[[i]] + guides(fill = "legend") + labs(fill="Condition")
  }
}
combined_boxplot <- wrap_plots(
  c(sid_plots, ds_plots),
  nrow = 2
) + plot_layout(axis_titles = "collect", guides="collect")
combined <- roc.plots_combined / combined_boxplot +
  plot_layout(heights = c(1, 2))
combined
```

```{r}
p_stacked <- plot_grid(auc_plot, combined, ncol = 1, align = "none", rel_heights = c(1, 1.2))
ggsave("./manuscript/f4.png", plot = p_stacked, width = 11, height = 11, dpi = 300)
```

